name: ldm
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - python=3.8
    - pytorch=1.11.0
    - torchvision=0.12.0
    - cudatoolkit=11.4
    - pip>=20.3
    - numpy>=1.19.2
    - pillow>=10.4.0
    - matplotlib>=3.6.2
    - pip:
        - albumentations==0.4.3
        - diffusers==0.14.0
        - einops==0.3.0
        - pytorch-lightning==1.4.2
        - kornia==0.6.0
        - opencv-python==4.1.2.30
        - pytorch-fid==0.3.0
        - transformers>=4.44.0
        - scikit-image>=0.20.0
        - scipy>=1.9.1
        - timm==0.6.13